#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: ubuntu:noble
  variables:
    DEBIAN_FRONTEND: noninteractive
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    MAVEN_HOME: /usr
    MAVEN_OPTS: -Xms256m -Xmx3072m
    PROTOBUF_HOME: /opt/protobuf
    PACKAGES: >
      ant apt-utils automake bats build-essential bzip2 libbz2-dev clang cmake curl
      libcurl4-openssl-dev doxygen fuse libfuse-dev gcc g++ git gnupg-agent hugo
      libbcprov-java libtool libssl-dev libprotobuf-dev libprotoc-dev libsasl2-dev
      libsnappy-dev libzstd-dev zlib1g-dev locales libtirpc-dev make
      openjdk-17-jdk pinentry-curses pkg-config python3
      python3-pip python3-pkg-resources python3-setuptools python3-wheel rsync
      shellcheck software-properties-common sudo valgrind yasm
  script:
    - apt-get update
    - cd dev-support/docker
    - chmod a+x pkg-resolver/*.sh pkg-resolver/*.py
    - chmod a+r pkg-resolver/*.json
    - apt-get install -y --no-install-recommends $PACKAGES
    - pkg-resolver/install-maven.sh ubuntu:noble
    - pkg-resolver/install-spotbugs.sh ubuntu:noble
    - pkg-resolver/install-boost.sh ubuntu:noble
    - pkg-resolver/install-protobuf.sh ubuntu:noble
    - pkg-resolver/install-intel-isa-l.sh ubuntu:noble
    - export PATH="${PATH}:/opt/protobuf/bin"
    - cd ../..
    - ./mvnw package -Pdist,native,yarn-ui -DskipTests -Dtar -Dhadoop-aws-package -q
  artifacts:
    paths:
      - hadoop-dist/target/hadoop-*.tar.gz
    expire_in: 1 day